### ISSUE TITLE
Using emojis as the text items

### ISSUE THREAD

**Issue by McGr** [an0/WLSegmentedControls#5]
When I use a list of emoji's as the items they show up fine when they are not selected,  but when they are selected they are replaced with a white rectangle

**Comment by an0** [comment]
There is no easy way to handle both bitmap(emoji) and vector glyphs simultaneously. If you only use emoji you can comment out [these two lines](https://github.com/an0/WLSegmentedControls/blob/master/WLSegmentedControls/WLSegment.m#L147-L148).
